/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import FormAutomobil.FormNoviAutomobil;
import FormAutomobil.FormPretragaAutomobila;
import controller.ClientController;
import domain.Administrator;
import javax.swing.JOptionPane;
import session.Session;

/**
 *
 * @author PC
 */
public class MainForm extends javax.swing.JFrame {

    Administrator ulogovani;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
        this.ulogovani = Session.getInstance().getUlogovani();
        lblUlogovani.setText("Ulogovani administrator: " + ulogovani);
        setTitle("Klijentska forma");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUlogovani = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        miNoviAuto = new javax.swing.JMenuItem();
        miPretragaAuta = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        miPretragaNarudzbine = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        miOdjava = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUlogovani.setText("Ulogovani");

        jMenu6.setText("Automobil");

        miNoviAuto.setText("Novi automobil");
        miNoviAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNoviAutoActionPerformed(evt);
            }
        });
        jMenu6.add(miNoviAuto);

        miPretragaAuta.setText("Pretraga automobila");
        miPretragaAuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaAutaActionPerformed(evt);
            }
        });
        jMenu6.add(miPretragaAuta);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Narudzbina");

        miPretragaNarudzbine.setText("Pretraga narudzbine");
        miPretragaNarudzbine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaNarudzbineActionPerformed(evt);
            }
        });
        jMenu7.add(miPretragaNarudzbine);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Odjava");

        miOdjava.setText("Odjavi se");
        miOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miOdjavaActionPerformed(evt);
            }
        });
        jMenu8.add(miOdjava);

        jMenuBar1.add(jMenu8);

        jMenu1.setText("Komponenta");

        jMenuItem1.setText("NovaKomponenta");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("pretragaKomponenti");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUlogovani)
                .addContainerGap(349, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUlogovani)
                .addContainerGap(341, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miNoviAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNoviAutoActionPerformed
        new FormNoviAutomobil(this, true).setVisible(true);
    }//GEN-LAST:event_miNoviAutoActionPerformed

    private void miPretragaAutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaAutaActionPerformed
        new FormPretragaAutomobila(this, true).setVisible(true);
    }//GEN-LAST:event_miPretragaAutaActionPerformed

    private void miPretragaNarudzbineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaNarudzbineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miPretragaNarudzbineActionPerformed

    private void miOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miOdjavaActionPerformed

        int result = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da "
                + "se odjavite?", "Konfirmacija", JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.NO_OPTION) {
            return;
        }

        if (result == JOptionPane.YES_OPTION) {
            new LoginForma().setVisible(true);
            Session.getInstance().setUlogovani(null);
            this.dispose();
        }

    }//GEN-LAST:event_miOdjavaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        new FormKomponenta.FormNovaKomponenta(this, true).setVisible(true);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       new FormKomponenta.FormPretragaKomponente(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lblUlogovani;
    private javax.swing.JMenuItem miNoviAuto;
    private javax.swing.JMenuItem miOdjava;
    private javax.swing.JMenuItem miPretragaAuta;
    private javax.swing.JMenuItem miPretragaNarudzbine;
    // End of variables declaration//GEN-END:variables

}
